[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]
runner = "./run_nonet.sh"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
